### PR TITLE
fix: ensure timestamp, block number, and parentHash are correct

### LINKED ISSUE #111: `block.timestamp` value varies within block
@vzts reported this behavior in [truffle 921](https://github.com/trufflesuite/truffle/issues/921) - there's more detail there. In summary it's unclear what the expected behavior is and @benjamincburns suggested we follow the other major clients, favoring static timestamps if there's no agreement.

Have just tested intra-block time values on `geth dev` and Parity POA over 4 calls at 1 second intervals: both have static timestamps. 

Will send a PR fixing this at [processCall](https://github.com/trufflesuite/ganache-core/blob/develop/lib/blockchain_double.js#L456) - just opening here in the meantime in case this change would impact any other timing related issues or there are implementation details to consider.

### PR DESCRIPTION
**Pull request by davidmurdoch**
Closes #111, supersedes PR #442

### CODE REVIEW

File: lib/blockchain_double.js [hunk 1]
```diff
@@ -354,12 +354,17 @@ BlockchainDouble.prototype.clearPendingTransactions = function() {
...
  */
-BlockchainDouble.prototype.createBlock = function(parent, callback) {
+BlockchainDouble.prototype.createBlock = function(parent, emulateParent, callback) {
   var self = this;
 
   if (typeof parent === "function") {
     callback = parent;
     parent = null;
+    emulateParent = false;
+  } else if (typeof emulateParent === "function") {
```
Comment (nicholasjpaterno) [inline lib/blockchain_double.js]: Looks like maybe we can reuse code here if we combine the conditions.

`typeof parent === "function" || typeof emulateParent === "function"`

Comment (davidmurdoch) [reply lib/blockchain_double.js]: Good catch. This was actually a bug in the logic. Fixing.
